version: '3.8'

services:
  db:
    image: mysql:8.0.38
    container_name: delivery-platform
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'delivery'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: